repos:
  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.6.9
    hooks:
      - id: ruff
        args: [--fix]
      - id: ruff-format
  - repo: local
    hooks:
      - id: check-untracked-migrations
        name: check-untracked-migrations
        entry: poetry run python manage.py makemigrations --check --dry-run
        language: system
        pass_filenames: false
      - id: check-absent-migrations
        name: check-absent-migrations
        entry: poetry run python manage.py makemigrations --check --dry-run
        language: system
        pass_filenames: false
